version: "3.8"
services:
  postgres:
    image: postgres:14.6
    ports:
        - 25432:5432
    healthcheck:
      test: ["CMD-SHELL", "PGPASSWORD=${DB_PASSWORD}", "pg_isready", "-U", "${DB_USERNAME}", "-d", "${DB_NAME}"]
      interval: 2s
      timeout: 60s
      retries: 5
      start_period: 80s 
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
  redis:
    image: redis:7.0
    ports:
      - 26379:6379
  python:
    build:
        context: .
        dockerfile: Dockerfile
    command: [sh, -c, "flask --app app init-db && flask --app app run -h 0.0.0.0 -p ${PORT}"] 
    ports:
        - ${PORT}:${PORT}
    depends_on:
        postgres:
          condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_HOST: redis
      REDIS_PORT: 6379
  